# Generated by Django 2.0.7 on 2018-08-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('background_color', models.CharField(max_length=255)),
                ('h1_color', models.CharField(max_length=255)),
                ('p_color', models.CharField(max_length=255)),
            ],
        ),
    ]
