# Generated by Django 2.0.7 on 2018-08-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('title1', models.CharField(max_length=50, verbose_name='A')),
                ('title2', models.CharField(max_length=50, verbose_name='B')),
                ('title3', models.CharField(max_length=50, verbose_name='C')),
            ],
        ),
    ]
